spring.application.name=petfinder-api
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/petfinder
spring.datasource.username=petfinder_user
spring.datasource.password=petfinder_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true