import type { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  filterContainer: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '20px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    marginBottom: '20px',
  },
  filterHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    paddingBottom: '10px',
    borderBottom: '1px solid #eee',
  },
  filterTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: '#1a1a1a',
  },
  resetButton: {
    background: 'none',
    border: 'none',
    color: '#06682D',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '8px',
    transition: 'background 0.2s',
  },
  filterSection: {
    marginBottom: '20px',
  },
  filterLabel: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 500,
    color: '#000000',
    marginBottom: '10px',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '8px',
  },
  option: {
    padding: '8px 12px',
    backgroundColor: '#f5f5f5',
    border: '1px solid #e0e0e0',
    borderRadius: '20px',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    color: '#000000',
    textAlign: 'center' as const,
  },
  optionActive: {
    padding: '8px 12px',
    backgroundColor: '#06682D',
    border: '1px solid #06682D',
    borderRadius: '20px',
    fontSize: '14px',
    cursor: 'pointer',
    color: '#ffffff',
    textAlign: 'center' as const,
  },
  distanceContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  rangeInput: {
    flex: 1,
    height: '4px',
    borderRadius: '2px',
    backgroundColor: '#e0e0e0',
    accentColor: '#06682D',
  },
  distanceValue: {
    minWidth: '50px',
    fontSize: '14px',
    color: '#666',
  },
  checkboxContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: '#06682D',
  },
  checkboxLabel: {
    fontSize: '14px',
    color: '#333',
    cursor: 'pointer',
  },
  hintText: {
    fontSize: '11px',
    color: '#000000',
    marginTop: '8px',
    marginBottom: 0,
  },
  // Estils per al modal mòbil
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 2000,
    display: 'flex',
    alignItems: 'flex-end' as const,
    justifyContent: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: '20px 20px 0 0',
    width: '100%',
    maxHeight: '80%',
    overflowY: 'auto' as const,
    padding: '20px',
    position: 'relative' as const,
  },
  modalCloseButton: {
    position: 'absolute' as const,
    top: '12px',
    right: '16px',
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#666',
  },
};