version: '3.8'

services:
  db:
    image: postgres:15
    container_name: petfinder_db
    restart: always
    environment:
      POSTGRES_USER: petfinder_user
      POSTGRES_PASSWORD: petfinder_pass
      POSTGRES_DB: petfinder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: